
def editDistance(s, t, m, n): #m = len(s), n = len(t)
	
	if(m == 0):
		return n;

	if(n == 0):
		return m;

	if(s[m-1] == t[n-1]):
		return editDistance(s, t, m-1, n-1)

	return 1 + min( editDistance(s,t, m-1, n),
					editDistance(s,t, m, n-1),
					editDistance(s,t , m-1, n-1))


s = 'VDCGDPSCRYLIKWHGETLFITQWYSTFYHIVKTGVTASIRVYVGHKAFNGTDCYPTELMGTINQRVSTFVQFCDPRYFFLVEAMQDSYAMRSAHGDFKLFCTKAQDYNSWFFNSWDENGTYKIIASKVYFKMYFEGRQKRVCSKHPRKSSTTCEMSFNQTANPRLMNRHEIEGFIFECHSWNTRKEFRTRWVLRYNAGLGAETFLIERCKIKEPTRSREWERYQNQHDFRKMADSCHVLARYHTYCCLKQWWGFKSTYRFHYHTWYECAIMSKVGYFFIWPEQSCLSSTSARSKNMDLQIFRFRNYPLCGHIWMEYRQLHRCKLQMWNVFTAGSWPKGRWTWSCIGPPQCHKMPRLGGNCSNWLAFCYEHPSCENMSPYEVMMRITECCAWKQEMFQFVWPQEFNYWHQRSWAEQYTFKWQCGAYRWGLWRCCIKFLDPANGYPQPSNVKWMECMYHHEMSKGILIMQGLAQNCAMMNMMYLVMSIMGFKRGSNTRVQHQAPQIRHRNTAMDIELPRTLLMQAVWMSSRCGFNATYVCWHIGNIKKWFAIGDILQWTGEFWRACWEPLADENGMGYLDWGGMYPMETNCHLKHHCGMAACQLMEPSAINSTQCHCSGNTPMQDLGHMMIVSTRDLLFLSKWSEWWRWFTGDVSHYENMNMVIFAVPISCECYTCFNRYIMGVGSIKVFCIYWNDNRPFTDEEGWDIWDIFWLKKLFHYFMRYCRLETISLNQICGFWRIQWDKLSKLHQDVEERYKVSWRFMEIKSCRKTVMAYGHETLDEQSDFLVKQALYKAVHNWDFEHSWWFSMEENSDKSFLWCKCEPCCNFWKRWTDPKIHVWLKDDETCEATPLDTYFNAQQVYSQVMWICLLMRFCHVDEPAP'
t = 'VGWTCWVQCGDPSCRYLIKITQWYSREHIVKTGVICFPKNIKATIRPYVGHKDAFNGTDCYNIEKMGGINQRVSTFVQFADPRYFFLVEAMQAHGAFKLFCTKAQDYHAWWKFTSHIFTLRGNFFNSWRRASKVYFKMYFEGRKRVCSKVKVEYVPRKPSTACANPRLMVHFARGFIFECQSINAENTQQYVLRYNAVLGAETFLIERCKIKRTRKFYRMMPTRSREHIHWERYKMADSCHVLARYHTYCCLKKSTYYFHYQKQEQVTSKVGYFEIWPEQSCLSSTSMRYKNWFGDCMACDLQPIYICNKFMRFRNYPLCIHIWMEYRQEHRCKLQMWNVFTAGSWHKTRWTWSCIGLRSAFNMPQYHKMPRLVKWVAFCKIRPAHPSWQNRSPRPEFDCKNAYFENLSPELKIDFQFVWPQEFNYWRSWAENYTFKWMCGAIRWGLWRCCIKFNGYPGPNDGVRVKWMSWMYHHEMSKGMQGLAQYCAMLPVWNMMYLVMSIMGFKRGSNTRVQHQAVLMELYTEIRHRNTAMRQNVYMQAVWMSSRCGFNSTYVCWHIGNIKKWFALQWTGEFWRACDENLMGIVPYHYPMRTEFNCHLKHPCGMAACQSMEPSIAWTKINKMYDLGHMMIVSTRDLLFLSKWSEWWRYENMNMVIFAVPITCNIECMHCYTCFNGSIKVFVIYWKEKTDERGPFQDEEGWRIWDQHPTERRTWLKCLFHSRHVATYCFMRYCRLETISLNQICGFWRIQWDKLSKLHQDVRFMEIKSCRKTVMALDHECLDCQSDFRTVKWPTVHNHIALYKSHHNWDFEHSWRPDFTMEQCSMEENSDKSFLWCKCEPCLNFWKRETEHVTRRIAEDDETCEATPGDTYFNAQQMYSQCMWICHKIMNNITEPAP'

m = len(s)
n = len(t)

s = [x for x in s]
t = [x for x in t]

import sys
class recursionlimit:
    def __init__(self, limit):
        self.limit = limit
        self.old_limit = sys.getrecursionlimit()

    def __enter__(self):
        sys.setrecursionlimit(self.limit)

    def __exit__(self, type, value, tb):
        sys.setrecursionlimit(self.old_limit)
with recursionlimit(1500000):
	print editDistance(s,t,m,n)